// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;
using WebTestEFCore20.Models;

namespace WebTestEFCore20.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20171011133055_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("WebTestEFCore20.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Number");

                    b.Property<int?>("OwnerId");

                    b.Property<decimal>("Saldo");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("WebTestEFCore20.Models.AccountOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("AccountOwner");

                    b.HasDiscriminator<string>("Discriminator").HasValue("AccountOwner");
                });

            modelBuilder.Entity("WebTestEFCore20.Models.LegalEntity", b =>
                {
                    b.HasBaseType("WebTestEFCore20.Models.AccountOwner");

                    b.Property<string>("LegalType");

                    b.Property<string>("Name");

                    b.ToTable("LegalEntity");

                    b.HasDiscriminator().HasValue("LegalEntity");
                });

            modelBuilder.Entity("WebTestEFCore20.Models.Person", b =>
                {
                    b.HasBaseType("WebTestEFCore20.Models.AccountOwner");

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("Family");

                    b.Property<string>("Name")
                        .HasColumnName("Person_Name");

                    b.ToTable("Person");

                    b.HasDiscriminator().HasValue("Person");
                });

            modelBuilder.Entity("WebTestEFCore20.Models.Account", b =>
                {
                    b.HasOne("WebTestEFCore20.Models.AccountOwner", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");
                });
#pragma warning restore 612, 618
        }
    }
}
